version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
  db:
      image: mysql:5.7
      command: mysqld --user=root
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - 3306
      volumes:
        - ./database/:/docker-entrypoint-initdb.d
        - my-db:/var/lib/mysql
volumes:
  my-db: